#!/usr/bin/env python
#-*- coding:utf-8 -*-
try:
  import unittest2 as unittest
except ImportError:
  import unittest
import os
import sys

project_root = os.path.split(os.path.abspath(os.path.dirname(__file__)))[0]

sys.path.insert(0, project_root)

loader = unittest.TestLoader()
# Run Tests
suite = loader.discover('tests', pattern='*_test.py', top_level_dir=project_root)
unittest.TextTestRunner(verbosity=1).run(suite)

# Run examples
suite = loader.discover('examples', pattern='*.py', top_level_dir=project_root)
unittest.TextTestRunner(verbosity=1).run(suite)

